services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecret
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  nats:
    image: nats
    volumes:
      - nats:/etc/nats
    command: -js
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
volumes:
  db:
    driver: local
  nats:
    driver: local
